logging:
#  config: classpath:logback-boot.xml
#  pattern:
#    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
#  path: log
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG

wechat:
  mp:
    appId: wx29042d05638e3b46
    secret: 52fef061a620eddc249885fc6795978a
    token: hjkjiot
    aesKey: RsmFdzocFXEfgzPb7oCkGnIrqGTPdkkYxnnj85hiWgb
  miniapp:
    appid: wxe577a8c9a04b0a6d
    secret: b423727cde584c61af6f1a43d9b4c5fb
    token: hjkjiot
    aesKey: RsmFdzocFXEfgzPb7oCkGnIrqGTPdkkYxnnj85hiWgb
    msgDataFormat: JSON
    
data:
  ponds:
    remove: true  # 当塘口删除时，是否物理删除相关数据
  device: 
    remove: false # 当设备删除时，是否物理删除相关数据

